---
- name: Create directory to store binary
  file:
    path: /opt/wildflyapp
    state: directory
- name: Copy jar file to the server
  copy:
    src: binaries/example-jaxrs-war-swarm.jar
    dest: /opt/wildflyapp/example-jaxrs-war-swarm.jar
    owner: "{{host_user}}"
    group: "{{host_user}}"
    mode: 0644
  notify: restart-wildfly
- name: Create service script
  template:
    src: roles/wildflyapp/files/wildflyapp.template
    dest: /lib/systemd/system/wildflyapp.service
    owner: root
    group: root
    mode: 0644
  notify: restart-wildfly
  no_log: true
- name: Reload systemd
  systemd:
    daemon_reload: yes
- name: Enable wildfly app service script
  systemd:
    name: wildflyapp
    enabled: yes
    masked: no
    state: started
  no_log: true
