---

- hosts:
    - "tag_identity_git"
    - "tag_identity_tower"
    - "tag_identity_system"
  connection: "local"
  gather_facts: false
  vars_files:
    - vars.yml

  tasks:
  - name: "Remove tagged EC2 instances from security group"
    ec2:
      state: "running"
      region: "{{ region }}"
      instance_ids: "{{ ec2_id }}"
      group_id: ""
    delegate_to: "localhost"

  - name: "Terminate tagged EC2 instances"
    ec2:
      state: "absent"
      region: "{{ region }}"
      instance_ids: "{{ ec2_id }}"
      wait: true
    delegate_to: "localhost"


- hosts: "localhost"
  connection: "local"
  gather_facts: false
  vars_files:
    - vars.yml
  tasks:
  - name: "Remove security group"
    ec2_group:
      name: "{{ security_group }}"
      region: "{{ region }}"
      state: "absent"
